version: "2"
services:

  nginx-rtmp:
    image: nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "1936:1936"
  processing-module:
    image: processing-module
    container_name: processor
    depends_on:
      - "nginx-rtmp"
    #volumes:
    #  - /usr/stream/ugly/ugly/ugly_restreamer_CV:/usr/stream

 #  ffmpeg:
 #   image: simple_ffmpeg
 #   container_name: ffmpeg
 #   command: sh -c 'sleep 1 && ffmpeg -re -i rtmp://nginx-rtmp:1935/live/test -c:v copy -b:a 160k -b:v 1M -f flv rtmp://nginx-rtmp:1936/processed/test'
